language: node_js
cache:
  - npm
node_js:
  - "4"
  - "5"
  - "6"
install:
  - npm install
before_script: "./bin/teo setup test"
script:
  - npm test
after_script: "gulp travis-test-cov && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"